spring:
  datasource:
    url: jdbc:mysql://124.70.94.151:3306/trsspider?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: trsspider
    password: gzXd7a3vguFkM94JoPS7

monitor:
  server:
    ip: 127.0.0.1
    # 开发环境监控端口示例
    ports: 3306,8080
  kafka:
    script-path: D:/temp/kafka-check.sh
  alarm:
    email-to: 735543130@qq.com