spring:
  datasource:
    url: jdbc:mysql:trsspider?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username:
    password:

monitor:
  server:
    ip:
    # 需求 6 要求的监控端口列表
    ports: 9092,9100,10086
  kafka:
    script-path: /data
  alarm:
    email-to: @qq.com
