spring:
  datasource:
    url: jdbc:mysql://124.70.94.151:3306/trsspider?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: trsspider
    password: gzXd7a3vguFkM94JoPS7

monitor:
  server:
    ip: 122.9.8.60
    # 需求 6 要求的监控端口列表
    ports: 9092,9100,10086
  kafka:
    script-path: /data/TRS/kafka_2.13-2.8.0/bin/kafka-consumer-groups.sh
  alarm:
    email-to: 735543130@qq.com